//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _54_LTUDDN_PhamTuanVu_DHTI15A14HN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class DiemThi
    {
        [Key, Column(Order = 0)]
        [Required]
        public int MaSV { get; set; }
        [Key, Column(Order = 1)]
        [Required]
        public string TenMT { get; set; }   
        [Required]
        public Nullable<int> SoTC { get; set; }
        [Required]
        public Nullable<System.DateTime> NgayThi { get; set; }
        [Required]
        [Range(0, 10)]
        public Nullable<decimal> Diem { get; set; }
    
        public virtual SinhVien SinhVien { get; set; }
    }
}
